# GitHub Labels Configuration
# Use with: gh label sync -f .github/labels.yml

# Priority labels
- name: 'priority: critical'
  color: 'd73a4a'
  description: 'Critical priority - security issues, data loss, complete breakage'

- name: 'priority: high'
  color: 'e99695'
  description: 'High priority - important features, major bugs'

- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority - nice to have features, minor bugs'

- name: 'priority: low'
  color: 'fef2c0'
  description: 'Low priority - cosmetic issues, far future features'

# Type labels
- name: 'type: bug'
  color: 'd73a4a'
  description: 'Something is not working correctly'

- name: 'type: feature'
  color: '0e8a16'
  description: 'New feature or enhancement request'

- name: 'type: documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: 'type: ci/cd'
  color: 'bfd4f2'
  description: 'Related to CI/CD pipelines and automation'

- name: 'type: dependencies'
  color: '0366d6'
  description: 'Dependency updates'

- name: 'type: security'
  color: 'ee0701'
  description: 'Security vulnerability or security-related issue'

- name: 'type: tests'
  color: '1d76db'
  description: 'Related to testing'

- name: 'type: refactoring'
  color: 'fbca04'
  description: 'Code refactoring without changing functionality'

- name: 'type: performance'
  color: 'f9d0c4'
  description: 'Performance improvements'

# Component labels
- name: 'component: core'
  color: '5319e7'
  description: 'servo-core crate'

- name: 'component: runtime'
  color: '7057ff'
  description: 'servo-runtime crate'

- name: 'component: lineage'
  color: 'b60205'
  description: 'servo-lineage crate'

- name: 'component: storage'
  color: 'c2e0c6'
  description: 'servo-storage crate'

- name: 'component: cloud-gcp'
  color: 'c5def5'
  description: 'servo-cloud-gcp crate'

- name: 'component: cli'
  color: 'fef2c0'
  description: 'servo-cli crate'

# Status labels
- name: 'status: blocked'
  color: 'd93f0b'
  description: 'Blocked by another issue or external dependency'

- name: 'status: stale'
  color: 'eeeeee'
  description: 'No activity for extended period'

- name: 'status: needs review'
  color: 'fbca04'
  description: 'Waiting for code review'

- name: 'status: needs info'
  color: 'd4c5f9'
  description: 'More information needed from author'

- name: 'status: in progress'
  color: 'c2e0c6'
  description: 'Currently being worked on'

# Size labels (for PRs)
- name: 'size/xs'
  color: '00ff00'
  description: 'Extra small PR (0-10 lines)'

- name: 'size/s'
  color: '7fff00'
  description: 'Small PR (11-100 lines)'

- name: 'size/m'
  color: 'ffff00'
  description: 'Medium PR (101-500 lines)'

- name: 'size/l'
  color: 'ff7f00'
  description: 'Large PR (501-1000 lines)'

- name: 'size/xl'
  color: 'ff0000'
  description: 'Extra large PR (1000+ lines)'

# Special labels
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention needed'

- name: 'breaking change'
  color: 'd73a4a'
  description: 'Introduces breaking changes to public API'

- name: 'duplicate'
  color: 'cfd3d7'
  description: 'This issue or PR already exists'

- name: 'invalid'
  color: 'e4e669'
  description: 'This issue is not valid'

- name: 'wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'

- name: 'database'
  color: 'c5def5'
  description: 'Database-related changes'

- name: 'config'
  color: 'd4c5f9'
  description: 'Configuration changes'

- name: 'work in progress'
  color: 'fbca04'
  description: 'Work in progress, not ready for review'
